### ISSUE TITLE
Suggestion: Transfer DB configuration information to be stored in a Environment File

### ISSUE THREAD

**Issue by davadams97** [DrewJKnowles/exercise-api#2]
https://github.com/DrewJKnowles/exercise-api/blob/6cbd6592e7f7074a74d87f1342c153b9d5f76c51/app.py#L11C1-L12C1

I think it is safer and much more cleaner to create an environment file and pass your environment details over there. This prevents you from accidentally committing DB secrets in the repository.

**Comment by DrewJKnowles** [comment]
@davadams97  I agree. My vision for this repo was to make a open-source version of it just something that is public then fork a private version for the version I want to deploy and sell. But I think I can just hide all of the sensitive information by storing those values in a environment file. Good Suggestion, will implement
